version: "3"
services:
  app:
    #container_name: test
    #restart: always
    build : .
    image: php_mongo_redis
    tty: true
    ports:
      - "5000:80"
      - "5002:8000"
    links:
      - mongo:"mongo"
      - redis:"redis"
    volumes:
      - .:/var/www/html
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    command: --loglevel verbose
    ports:
      - "6379:6379"